ipynb에서 python 파일로 옮기기
stayjungle/fsk-fcdb pull request #2
Opened 2022-05-27 02:21 UTC by dahyun-ruru

브랜치 명을 develop에서 ipynb-to-py로 변경하면서 브랜치가 삭제되고, 기존 PR이 닫혀서 새로 생성하였습니다. 

1. 파일명에 공백이 들어가지 않도록 수정하고, 최신 버전 파일만 남겨두었습니다.
2. csv로 저장할 때 인덱스 칼럼을 제외하고 저장하도록 하였습니다.
3. 주석 및 커밋 코멘트를 한국어로 수정하였습니다. 
4. 칼럼-단위 메타 테이블 생성은 다른 브랜치로 작업하겠습니다.

2022-06-03 06:35 UTC, ak-stayjungle commented
`df_sample-cleansed-waterfiber.csv`는 내용이 비어있는데 혹시 `df_sample.xlsx` 파일에 관련 샘플이 없어서일까요?

2022-06-03 08:53 UTC, dahyun-ruru commented
- [ ] unit test 만들기
 - [ ] df_sample.xlsx 샘플링 다시

2022-06-07 06:12 UTC, dahyun-ruru commented
@ak-stayjungle 규영님 df_sample.xlsx 파일 수정하고, pytest 추가하였습니다. 리뷰 부탁드립니다!

2022-06-08 00:58 UTC, ak-stayjungle requested changes
단위 테스트가 있으니 한결 리뷰하기가 좋아요. 고생하셨습니다.

몇 가지 수정 의견을 남겼습니다.

2022-06-08 00:58 UTC, ak-stayjungle commented on fcdb_cleanse.py
> +        df.loc[mask, '내용량_단위'] = value
for-loop 대신 UNITS를 데이터프레임으로 만든 뒤 [merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html) 하도록 바꿔보면 좋겠습니다.

2022-06-08 00:58 UTC, ak-stayjungle commented on fcdb_cleanse.py
> +    for key, value in UNITS.items():
여기도 for-loop 없이 구현할 방법을 찾아보시겠어요? 1시간 정도 시도해보고 어려우면 말씀해주세요. 같이 해봅시다.

2022-06-08 00:58 UTC, ak-stayjungle commented on tests/test.py
> +def test_내용량_단위_빈값_채우기(df):
테스트 이름을 국문으로 바꾸고 assert의 두번째 인자(테스트가 깨진 이유를 설명)를 제거했습니다. 다른 테스트도 이런 식으로 바꿔보면 좋겠습니다. 하나의 테스트 케이스가 되도록 한 측면만 테스트하도록 나누고, 각 테스트 케이스가 어떤 측면을 테스트하는지 구체적으로 설명하는 이름을 국문으로 지어주면 assert의 두번째 인자를 쓸 필요가 줄어듭니다.

2022-06-08 00:58 UTC, ak-stayjungle commented on fcdb_cleanse.py
> +    df.drop([col1, col2], axis=1, inplace=True)
이 함수에 대한 단위 테스트도 추가해주시겠어요?

2022-06-08 00:58 UTC, ak-stayjungle commented on fcdb_cleanse.py
> +    """칼럼 n에 칼럼 c 값을 k배 곱하여 복사, 칼럼 c 드랍"""
주석에는 함수의 구체적 실행 절차가 아니라 함수가 하는 일(또는 목적)을 적어주면 좋습니다. 어떤 상황에서 쓰이는 함수인지 알 수 있도록 주석을 고쳐주세요 :)

2022-06-08 00:58 UTC, ak-stayjungle commented on tests/test.py
> +def test_make_new_column(df):
하나의 테스트 케이스에서 너무 많은 로직을 검사하는 것 같아요. 여러 테스트케이스로 분리해보면 어떨까요?

2022-06-10 11:03 UTC, dahyun-ruru commented on tests/test.py
> +def test_총내용량_둘다_있는값_오기입_삭제(df):
@ak-stayjungle 규영님, 이 부분 왜 drop_both_value(df) 함수 적용하지 않아도 pass 되는지 알아봤는데
mask.isna().any()가 제가 의도한 test 값이 아닌 것 같습니다.

![image](https://user-images.githubusercontent.com/104582764/173051717-3d4b9ee7-f249-41ea-9c31-b0cee6ee41c6.png)


df[mask] 값은 5행이 존재하는데, mask.isna() 출력하면 저 tail 5행이 False로 나와서 어떤 경우에도 mask.isna().any()가False인 것 같습니다.

2022-06-10 11:20 UTC, dahyun-ruru commented on tests/test.py
> +def test_총내용량_둘다_있는값_오기입_삭제(df):
그래서 `mask.any()` 로 해결하였습니다. 다른 test 함수에서도 `mask.isna().any()`인 부분 모두 수정하였습니다.

2022-06-12 11:36 UTC, ak-stayjungle commented
수고하셨습니다. 일단 머지를 하고 추가로 고칠 부분들이 있다면 더 고치는걸로 합시다 :)

몇 가지 소소한 피드백입니다.

- 커밋 메시지에 의도를 조금만 더 잘 남겨주시면 좋겠습니다. 제목에 다 담기 어려우면 본문에 부연 설명을 적어주시면 좋아요.
- 커밋 메시지와 실제 커밋한 내용이 일치하도록 해주세요. 예를 들어 커밋 메시지가 "for 문 수정"이라면 되도록 for문만 수정한 커밋이 담겨야 합니다. 변수 이름을 바꿨거나 포매팅을 수정했다면 해당 커밋은 별도로 분리해주시면 리뷰하기가 좋습니다.

2022-06-12 11:36 UTC, merged